import type { ModelProfile } from "./types";

/**
 * Stable SakthiAI execution profiles.
 *
 * These are capability envelopes, not claims that a specific model has already
 * been deployed. Runtime integration stays disabled until a concrete local or
 * self-hosted engine is separately qualified with evidence.
 */
export const MODEL_CATALOG: readonly ModelProfile[] = [
  {
    id: "sakthi-local-lite",
    label: "Sakthi Local Lite",
    family: "sakthiai-local",
    providerKind: "local",
    billingMode: "local_compute",
    openWeights: true,
    requiresApiKey: false,
    runtimeEnabled: false,
    implementationStatus: "planned",
    capabilities: ["chat", "structured_output", "multilingual", "tool_use"],
    preferredIntents: ["conversation", "document_work"],
    reasoningEfforts: ["none", "low"],
    qualityTier: 2,
    resourceFloor: { cpuCores: 2, ramGb: 8, vramGb: 0, gpuCount: 0 },
    notes: "Control-plane/dev profile intended for compact open-weight models; no runtime is claimed yet.",
  },
  {
    id: "sakthi-local-general",
    label: "Sakthi Local General",
    family: "sakthiai-local",
    providerKind: "self_hosted",
    billingMode: "local_compute",
    openWeights: true,
    requiresApiKey: false,
    runtimeEnabled: false,
    implementationStatus: "planned",
    capabilities: [
      "chat",
      "reasoning",
      "coding",
      "long_context",
      "tool_use",
      "research",
      "agents",
      "structured_output",
      "multilingual",
    ],
    preferredIntents: ["analysis", "research", "coding", "document_work", "automation"],
    reasoningEfforts: ["none", "low", "medium", "high"],
    qualityTier: 3,
    resourceFloor: { cpuCores: 4, ramGb: 16, vramGb: 8, gpuCount: 1 },
    notes: "General self-hosted profile for a qualified quantized open-weight model; engine/model choice is deferred.",
  },
  {
    id: "sakthi-local-reasoner",
    label: "Sakthi Local Reasoner",
    family: "sakthiai-local",
    providerKind: "self_hosted",
    billingMode: "local_compute",
    openWeights: true,
    requiresApiKey: false,
    runtimeEnabled: false,
    implementationStatus: "planned",
    capabilities: [
      "chat",
      "reasoning",
      "coding",
      "long_context",
      "tool_use",
      "research",
      "agents",
      "structured_output",
      "multilingual",
    ],
    preferredIntents: ["analysis", "research", "coding", "automation"],
    reasoningEfforts: ["low", "medium", "high", "max"],
    qualityTier: 4,
    resourceFloor: { cpuCores: 8, ramGb: 32, vramGb: 16, gpuCount: 1 },
    notes: "Higher-reasoning local profile. Resource floor is a routing guard, not a performance guarantee.",
  },
  {
    id: "sakthi-local-multimodal",
    label: "Sakthi Local Multimodal",
    family: "sakthiai-local",
    providerKind: "self_hosted",
    billingMode: "local_compute",
    openWeights: true,
    requiresApiKey: false,
    runtimeEnabled: false,
    implementationStatus: "planned",
    capabilities: [
      "chat",
      "reasoning",
      "vision",
      "tool_use",
      "agents",
      "structured_output",
      "multilingual",
    ],
    preferredIntents: ["vision", "analysis", "document_work"],
    reasoningEfforts: ["low", "medium", "high"],
    qualityTier: 3,
    resourceFloor: { cpuCores: 8, ramGb: 32, vramGb: 16, gpuCount: 1 },
    notes: "Vision-capable self-hosted profile; speech/image/video generation remain separate engines.",
  },
  {
    id: "frontier-external-reference",
    label: "Frontier External Reference",
    family: "external-frontier",
    providerKind: "external",
    billingMode: "metered_api",
    openWeights: false,
    requiresApiKey: true,
    runtimeEnabled: false,
    implementationStatus: "reference_only",
    capabilities: [
      "chat",
      "reasoning",
      "coding",
      "vision",
      "long_context",
      "tool_use",
      "research",
      "computer_use",
      "agents",
      "structured_output",
      "multilingual",
    ],
    preferredIntents: [
      "conversation",
      "analysis",
      "research",
      "coding",
      "document_work",
      "data_analysis",
      "browser_work",
      "automation",
      "vision",
      "creative",
    ],
    reasoningEfforts: ["none", "low", "medium", "high", "max"],
    qualityTier: 5,
    resourceFloor: { cpuCores: 1, ramGb: 1, vramGb: 0, gpuCount: 0 },
    notes: "Architecture reference only. No API key, billing or external provider is enabled by this foundation.",
  },
] as const;

export function getModelProfile(id: string): ModelProfile | undefined {
  return MODEL_CATALOG.find(model => model.id === id);
}
