import { createHash, randomBytes } from "node:crypto";
import { sql } from "drizzle-orm";
import type { drizzle } from "drizzle-orm/mysql2";

/**
 * OAuth login transactions.
 *
 *   begin(nonce, challenge)   server issues a transaction (nonce is generated by the server, TTL 10 min)
 *   consume(nonce, challenge) atomically marks it used; true only for the FIRST valid consumer
 *
 * The MySQL implementation is shared by every instance. Time comparisons use the DATABASE clock so instance clock
 * skew cannot extend or shorten a transaction. Only SHA-256 digests are persisted. Every failure mode (unknown,
 * wrong challenge, expired, replayed, malformed input, database error) results in refusal; a database error is thrown
 * so the caller can answer 503 instead of guessing.
 */
export const LOGIN_TRANSACTION_TTL_SECONDS = 600;
const NONCE = /^[A-Za-z0-9_-]{32,128}$/;
const CHALLENGE = /^[A-Za-z0-9_-]{43}$/; // BASE64URL(SHA-256) without padding

export interface LoginTransactionStore {
  begin(nonce: string, challenge: string): Promise<void>;
  consume(nonce: string, challenge: string): boolean | Promise<boolean>;
}

export const newLoginNonce = () => randomBytes(32).toString("base64url");
export const isWellFormedChallenge = (value: unknown): value is string => typeof value === "string" && CHALLENGE.test(value);
export const isWellFormedNonce = (value: unknown): value is string => typeof value === "string" && NONCE.test(value);
const digest = (value: string) => createHash("sha256").update(value, "utf8").digest("hex");

/** In-process store for tests and database-less development. Not shared between instances. */
export class MemoryLoginTransactionStore implements LoginTransactionStore {
  private readonly rows = new Map<string, { challengeHash: string; expiresAt: number; consumed: boolean }>();
  constructor(private readonly ttlMs = LOGIN_TRANSACTION_TTL_SECONDS * 1000, private readonly now: () => number = Date.now) {}
  async begin(nonce: string, challenge: string) {
    if (!isWellFormedNonce(nonce) || !isWellFormedChallenge(challenge)) throw new Error("malformed login transaction");
    const now = this.now();
    for (const [key, row] of this.rows) if (row.expiresAt + 60_000 <= now) this.rows.delete(key);
    this.rows.set(digest(nonce), { challengeHash: digest(challenge), expiresAt: now + this.ttlMs, consumed: false });
  }
  consume(nonce: string, challenge: string) {
    if (!isWellFormedNonce(nonce) || !isWellFormedChallenge(challenge)) return false;
    const row = this.rows.get(digest(nonce));
    if (!row || row.consumed || row.expiresAt <= this.now() || row.challengeHash !== digest(challenge)) return false;
    row.consumed = true;
    return true;
  }
}

type Db = ReturnType<typeof drizzle>;
type Header = { affectedRows?: number };
const affected = (result: unknown) => Number(((Array.isArray(result) ? result[0] : result) as Header)?.affectedRows ?? 0);

export class MysqlLoginTransactionStore implements LoginTransactionStore {
  constructor(private readonly getDb: () => Promise<Db | null | undefined>, private readonly ttlSeconds = LOGIN_TRANSACTION_TTL_SECONDS) {}

  private async db(): Promise<Db> {
    const db = await this.getDb();
    if (!db) throw new Error("database unavailable");
    return db;
  }

  async begin(nonce: string, challenge: string): Promise<void> {
    if (!isWellFormedNonce(nonce) || !isWellFormedChallenge(challenge)) throw new Error("malformed login transaction");
    const db = await this.db();
    await db.execute(sql`INSERT INTO oauthLoginTransactions (nonceHash, challengeHash, createdAt, expiresAt)
      VALUES (${digest(nonce)}, ${digest(challenge)}, NOW(3), DATE_ADD(NOW(3), INTERVAL ${this.ttlSeconds} SECOND))`);
  }

  /** One conditional UPDATE: InnoDB row locking lets exactly one concurrent caller see affectedRows = 1. */
  async consume(nonce: string, challenge: string): Promise<boolean> {
    if (!isWellFormedNonce(nonce) || !isWellFormedChallenge(challenge)) return false;
    const db = await this.db();
    const result = await db.execute(sql`UPDATE oauthLoginTransactions SET consumedAt = NOW(3)
      WHERE nonceHash = ${digest(nonce)} AND challengeHash = ${digest(challenge)} AND consumedAt IS NULL AND expiresAt > NOW(3)`);
    return affected(result) === 1;
  }

  /** Removes transactions that expired more than `graceSeconds` ago. Live (unexpired) transactions are never touched. */
  async cleanup(graceSeconds = 60, limit = 1000): Promise<number> {
    const db = await this.db();
    const result = await db.execute(sql`DELETE FROM oauthLoginTransactions WHERE expiresAt < DATE_SUB(NOW(3), INTERVAL ${Math.max(0, Math.floor(graceSeconds))} SECOND) LIMIT ${Math.max(1, Math.floor(limit))}`);
    return affected(result);
  }
}

let shared: LoginTransactionStore | null = null;
/** MySQL when DATABASE_URL is configured (multi-instance safe); otherwise process-local memory (development/tests only). */
export function getLoginTransactionStore(getDb: () => Promise<Db | null | undefined>): LoginTransactionStore {
  if (!shared) {
    if (process.env.DATABASE_URL) {
      const store = new MysqlLoginTransactionStore(getDb);
      const timer = setInterval(() => { store.cleanup().catch(() => undefined); }, 5 * 60 * 1000);
      timer.unref?.();
      shared = store;
    } else shared = new MemoryLoginTransactionStore();
  }
  return shared;
}
export const resetLoginTransactionStoreForTests = () => { shared = null; };
