/**
 * Tenant-safe authorization for stored objects.
 *
 * An object key supplied by a caller is untrusted input. It is never parsed for
 * user/workspace identifiers and never used to decide access. Access is decided
 * only by the workspace that owns the persisted row referencing that exact key
 * (documents.storageKey / creatorAssets.storageKey) and the caller's membership
 * of that workspace (workspaceMembers).
 */

export const MAX_STORAGE_KEY_LENGTH = 1024;

const CONTROL_CHARACTERS = /[\u0000-\u001F\u007F]/;
const LONE_SURROGATE = /[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/;

/**
 * Structural validation only (defense in depth). Returns the key unchanged when
 * it is a well-formed relative object key, otherwise null. Passing this check
 * grants nothing: the key must still match a persisted row the caller may access.
 */
export function parseStorageObjectKey(raw: unknown): string | null {
  if (typeof raw !== "string") return null;
  if (raw.length === 0 || raw.length > MAX_STORAGE_KEY_LENGTH) return null;
  if (CONTROL_CHARACTERS.test(raw) || LONE_SURROGATE.test(raw)) return null;
  // Keys generated by SakthiAI never contain backslashes or percent signs, so
  // encoded/double-encoded separators and traversal attempts are rejected here.
  if (raw.includes("\\") || raw.includes("%")) return null;
  if (raw.startsWith("/")) return null;

  for (const segment of raw.split("/")) {
    if (segment === "" || segment === "." || segment === "..") return null;
  }
  return raw;
}

export type StorageObjectOwner = { workspaceId: number; storageKey: string | null };

export type StorageAccessDependencies = {
  /** Persisted rows whose storage key matches `key` (database comparison may be case-insensitive). */
  findOwners: (key: string) => Promise<StorageObjectOwner[]>;
  /** Existing tenant model: resolves only when `userId` is a member of `workspaceId`. */
  getWorkspaceForUser: (userId: number, workspaceId: number) => Promise<unknown | undefined>;
};

/**
 * Resolves `rawKey` to the storage key of a persisted object the user may access,
 * or null (unknown, malformed or forbidden — callers must not distinguish these).
 * The returned value is the key as persisted in the database, never the caller's input.
 */
export async function resolveAuthorizedStorageKey(
  user: { id: number },
  rawKey: unknown,
  deps: StorageAccessDependencies,
): Promise<string | null> {
  const key = parseStorageObjectKey(rawKey);
  if (!key) return null;

  const owners = await deps.findOwners(key);
  for (const owner of owners) {
    // Binary-exact comparison: the SQL collation may be case/accent-insensitive.
    if (owner.storageKey !== key) continue;
    if (!Number.isInteger(owner.workspaceId) || owner.workspaceId <= 0) continue;
    if (await deps.getWorkspaceForUser(user.id, owner.workspaceId)) return owner.storageKey;
  }
  return null;
}
