import type { SkillProfile } from "./types";

/**
 * Provider-independent SakthiAI skill catalog.
 * Profiles are control-plane declarations only; they do not activate external tools.
 */
export const SKILL_CATALOG: readonly SkillProfile[] = [
  {
    id: "retrieval.read",
    label: "Knowledge Retrieval",
    kind: "retrieval",
    description: "Read tenant-scoped indexed knowledge and provenance without mutation.",
    sideEffect: "none",
    risk: "low",
    enabled: true,
    requiresNetwork: false,
    requiresCredential: false,
    requiresHumanApproval: false,
    meteredSpendPossible: false,
    tenantScoped: true,
  },
  {
    id: "code.analyze",
    label: "Code Analysis",
    kind: "code",
    description: "Inspect source, reason about changes and produce a bounded edit plan without writing.",
    sideEffect: "none",
    risk: "low",
    enabled: true,
    requiresNetwork: false,
    requiresCredential: false,
    requiresHumanApproval: false,
    meteredSpendPossible: false,
    tenantScoped: true,
  },
  {
    id: "code.write",
    label: "Code Edit",
    kind: "code",
    description: "Apply code changes inside an approved workspace or sandbox.",
    sideEffect: "local_write",
    risk: "medium",
    enabled: false,
    requiresNetwork: false,
    requiresCredential: false,
    requiresHumanApproval: false,
    meteredSpendPossible: false,
    tenantScoped: true,
  },
  {
    id: "browser.read",
    label: "Browser Read",
    kind: "browser",
    description: "Navigate and read public or explicitly authorised web resources without mutation.",
    sideEffect: "none",
    risk: "medium",
    enabled: false,
    requiresNetwork: true,
    requiresCredential: false,
    requiresHumanApproval: false,
    meteredSpendPossible: false,
    tenantScoped: true,
  },
  {
    id: "browser.action",
    label: "Browser Action",
    kind: "browser",
    description: "Perform externally visible browser actions only inside an approved bounded workflow.",
    sideEffect: "external_write",
    risk: "high",
    enabled: false,
    requiresNetwork: true,
    requiresCredential: true,
    requiresHumanApproval: true,
    meteredSpendPossible: false,
    tenantScoped: true,
  },
  {
    id: "connector.read",
    label: "Connector Read",
    kind: "connector",
    description: "Read data from an authorised connector under tenant scope.",
    sideEffect: "none",
    risk: "medium",
    enabled: false,
    requiresNetwork: true,
    requiresCredential: true,
    requiresHumanApproval: false,
    meteredSpendPossible: false,
    tenantScoped: true,
  },
  {
    id: "connector.write",
    label: "Connector Write",
    kind: "connector",
    description: "Mutate an external connected system after explicit policy and approval checks.",
    sideEffect: "external_write",
    risk: "high",
    enabled: false,
    requiresNetwork: true,
    requiresCredential: true,
    requiresHumanApproval: true,
    meteredSpendPossible: false,
    tenantScoped: true,
  },
  {
    id: "deployment.release",
    label: "Deployment / Release",
    kind: "deployment",
    description: "Change a runtime or release state after exact-head, evidence and owner-approval gates.",
    sideEffect: "privileged",
    risk: "critical",
    enabled: false,
    requiresNetwork: true,
    requiresCredential: true,
    requiresHumanApproval: true,
    meteredSpendPossible: true,
    tenantScoped: true,
  },
];

export function getSkillProfile(id: string): SkillProfile | undefined {
  return SKILL_CATALOG.find(skill => skill.id === id);
}
